twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        newsActivitiesSinceLastLogin: '@App\Service\NewsActivitiesSinceLastLoginService'

when@test:
    twig:
        strict_variables: true
